# Generated by Django 2.1.8 on 2019-09-18 09:32

import autoslug.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default='', editable=False, populate_from='title', unique=True)),
                ('author', models.CharField(default='', max_length=200, verbose_name='Author')),
                ('description', models.TextField(default='', verbose_name='Description')),
                ('article_image', models.ImageField(upload_to='', verbose_name='Article Image')),
                ('article_text', models.TextField(default='', verbose_name='Article text')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
