# Generated by Django 2.1.8 on 2019-09-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img2',
            field=models.ImageField(default='', upload_to='', verbose_name='Article Image 2'),
        ),
        migrations.AddField(
            model_name='article',
            name='img3',
            field=models.ImageField(default='', upload_to='', verbose_name='Article Image 3'),
        ),
        migrations.AddField(
            model_name='article',
            name='img4',
            field=models.ImageField(default='', upload_to='', verbose_name='Article Image 4'),
        ),
        migrations.AddField(
            model_name='article',
            name='img5',
            field=models.ImageField(default='', upload_to='', verbose_name='Article Image 5'),
        ),
        migrations.AddField(
            model_name='article',
            name='img6',
            field=models.ImageField(default='', upload_to='', verbose_name='Article Image 6'),
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
