# Generated by Django 2.1.8 on 2019-09-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190920_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='img2',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Article Image 2'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img3',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Article Image 3'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img4',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Article Image 4'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img5',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Article Image 5'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img6',
            field=models.ImageField(blank=True, default='', upload_to='', verbose_name='Article Image 6'),
        ),
    ]
