# Generated by Django 2.1.8 on 2019-09-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190923_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='', on_delete='models.CASCADE', to='news.Category'),
        ),
    ]
