# Generated by Django 2.1.8 on 2019-09-23 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190923_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='article_category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_title',
        ),
    ]
