# Generated by Django 2.1.8 on 2019-09-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20190926_1035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_image',
        ),
        migrations.AddField(
            model_name='articleimages',
            name='article',
            field=models.ForeignKey(on_delete='models.CASCADE', to='news.Article'),
        ),
    ]
