# Generated by Django 2.1.8 on 2019-09-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20190926_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimages',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='article',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='Images', to='news.Article'),
        ),
    ]
