# Generated by Django 2.1.8 on 2019-09-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20190926_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimages',
            name='article',
            field=models.OneToOneField(on_delete='models.CASCADE', related_name='img', to='news.Article'),
        ),
        migrations.AlterField(
            model_name='articleimages',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
