# Generated by Django 2.1.8 on 2019-09-26 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_auto_20190926_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimages',
            name='article',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='image', to='news.Article'),
        ),
    ]
