# Generated by Django 2.1.8 on 2019-09-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20190926_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimages',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
