# Generated by Django 2.1.8 on 2019-09-27 09:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20190926_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
