# Generated by Django 2.1.8 on 2019-09-27 10:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_auto_20190927_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=tinymce.models.HTMLField(default='', verbose_name='Article text'),
        ),
    ]
