# Generated by Django 2.1.8 on 2019-09-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20190927_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimages',
            name='name',
        ),
    ]
