# Generated by Django 2.1.8 on 2019-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_remove_articleimages_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimages',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='articleimages',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
