# Generated by Django 2.1.8 on 2019-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20190927_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete='models.CASCADE', to='news.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
