# Generated by Django 2.1.8 on 2019-10-01 19:48

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_auto_20191001_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_text',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Article text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
