# Generated by Django 2.1.8 on 2019-10-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='apartment',
        ),
        migrations.AddField(
            model_name='apartment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='booking.Reservation'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
