# Generated by Django 2.1.8 on 2019-10-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20191010_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', related_name='reservation', to='booking.Reservation'),
        ),
    ]
