# Generated by Django 2.1.8 on 2019-10-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20191010_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='booking.Reservation'),
        ),
    ]
