# Generated by Django 2.1.8 on 2019-10-10 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20191010_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='booking.Apartment'),
        ),
    ]
