# Generated by Django 2.1.8 on 2019-10-10 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20191010_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reservation',
        ),
        migrations.AddField(
            model_name='reservation',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='booking.Apartment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
