# Generated by Django 2.1.8 on 2019-10-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20191010_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='in_rent',
        ),
        migrations.AddField(
            model_name='apartmentimages',
            name='apartment',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='apartment', to='booking.Apartment'),
        ),
    ]
