# Generated by Django 2.1.8 on 2019-10-13 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20191013_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='photo_1',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='photo_4',
        ),
    ]
