# Generated by Django 2.1.8 on 2019-10-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20191013_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartmentimages',
            name='apartment',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='image', to='booking.Apartment'),
        ),
    ]
