# Generated by Django 2.1.8 on 2019-10-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_auto_20191013_1436'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentPrices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_start_date', models.DateField(blank=True, null=True)),
                ('price_end_date', models.DateField(blank=True, null=True)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='price',
            new_name='apartment_price',
        ),
        migrations.AddField(
            model_name='apartmentprices',
            name='apartment',
            field=models.ForeignKey(on_delete='models.CASCADE', related_name='price', to='booking.Apartment'),
        ),
    ]
